name: shareover
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.0
  shared_preferences: ^2.0.15
  google_maps_flutter: ^2.1.8
  location:
    git:
      url: https://github.com/781flyingdutchman/flutterlocation.git
      ref: V4
      path: packages/location
  sliding_up_panel: ^2.0.0+1
  openapi_generator_annotations: ^4.10.0
  image: ^4.0.17
  date_field: ^3.0.5
  intl: ^0.18.1
  shareover_api:
    path: api/shareover_api

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_maps_flutter_web: ^0.4.0+9

dev_dependencies:
  flutter_test:
    sdk: flutter
  openapi_generator: ^4.10.0
  flutter_lints: ^2.0.0
  build_runner:

flutter:

  uses-material-design: true
  assets:
    - assets/map_style.json

